### ISSUE TITLE
Create torrent?

### ISSUE THREAD

**Issue by dessalines** [ludviglundgren/qbittorrent-cli#101]
qbittorrent has the ability to create torrents from a file / directory, but I don't see that here.

**Comment by ludviglundgren** [comment]
Hi!

While qbittorrent does support it, it's not that straight forward to implement it via their API. There's other existing cli tools like `mktorrent`, `imdl` and `torrenttools` that works well on cli. I'd recommend to use those :)

**Comment by dessalines** [comment]
Gotcha, up to you if you'd like to close this then.
