### ISSUE TITLE
[FEATURE REQ] Set download location

### ISSUE THREAD

**Issue by ActionHudson** [ludviglundgren/qbittorrent-cli#106]
Add a command to pass in the folder location for download.

**Comment by ludviglundgren** [comment]
For which command? `torrent add`? If yes, then that is already supported with `--save-path DIR`. Can also be controlled with setting a savepath in a category and setting the category with `--category=MYCATEGORY`.

Try it out and report back if you have any issues.

**Comment by chungyinleo** [comment]
Why is the download location still the default location even if I set it to a different directory with `--save-path DIR`?
