### ISSUE TITLE
Site dosent work

### ISSUE THREAD

**Issue by Tarbian** [ludviglundgren/qbittorrent-cli#36]
I got this error
`qbt list `
`login error: Post "http://127.0.0.1:6776/api/v2/auth/login": dial tcp 127.0.0.1:6776: connect: connection refused`

**Comment by ludviglundgren** [comment]
Hi! That looks like a port which might be used as the bittorrent port, and not the WebUI port. Try change that. 

And did you add the config with username and password as well?

**Comment by Tarbian** [comment]
Changing the port in the config did not help. I reinstalled completely and everything worked
