### ISSUE TITLE
I am having this error

### ISSUE THREAD

**Issue by lucasmz1** [ludviglundgren/qbittorrent-cli#37]
login error: Post "http://127.0.0.1:6776/api/v2/auth/login": dial tcp 127.0.0.1:6776: connect: connection refused
how do I solve it?

this below is the command line I am trying to input ./qbt add --magnet magnet:?xt=urn:btih:6429b3fe8614b55b429bc2eb023e1553118ec2f2&dn=Samaritano%202022%201080p%20WEB-DL%20DUAL%205.1&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a80%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce

**Comment by A-Sai-Chaithanya** [comment]
This can be a common issue if the port specified in the config file is being used by another process. Change the port number in the main config file and try again.
