### ISSUE TITLE
Using import requires both --source-dir --qbit-dir to have trailing slash

### ISSUE THREAD

**Issue by runaroundhome** [ludviglundgren/qbittorrent-cli#38]
I bumped into this issue today, not thinking it would be an issue having a trailing slash or not.

I had the following.

    qbt import --source rtorrent --source-dir '/rtorrent/session' --qbit-dir '/qBittorrent/BT_backup' --dry-run

Which just got me `Total torrents to process: 0`, couldn't figure out what was going on, done a google and come across this reddit comment about it, turns out both source and dest need a trailing slash.

This then worked.

    qbt import --source rtorrent --source-dir '/rtorrent/session/' --qbit-dir '/qBittorrent/BT_backup/' --dry-run

Another user having the same issue: https://www.reddit.com/r/seedboxes/comments/pidhbd/comment/hbphs8f/?utm_source=share&utm_medium=web2x&context=3

Think it would be helpful to other users if you could leave a note in the documentation, or add the trailing slash in code if it's missing.

PS, this is meant to be constructive feedback, I really like what you have made, thank you!

**Comment by ludviglundgren** [comment]
@runaroundhome Sorry for the months of silence! This is now fixed in `develop`. Will release a new version soon!
