### ISSUE TITLE
Move not working on qBit 4.5.2

### ISSUE THREAD

**Issue by wastingaeons** [ludviglundgren/qbittorrent-cli#46]
First of all thank you for this tool! 

While trying to use the 'move' option I get a successful message but categories remain unchanged. I don't see any pertinent info in qbit logs other than a successful web login. 

However when manually changing a torrents category in web-ui there is related info in the log. Let me know if I can provide more info.

**Edit:** Looks to may be a 4.5.x issue - move works as intended on 4.3.9

```
qbittorrent version: qbittorrent-nox v4.5.2 on debian
qbt-cli version: tried dev / 1.0.0 / 0.16.0
```
```
qbt move --from t1 --to t2

Found 1 matching torrents to move from (t1) to (t2)
Successfully moved 1 torrents from (t1) to (t2)
```

**Comment by ludviglundgren** [comment]
Happy you like it! Qbit changed the allowed http methods in 4.4.x or 4.5.x and is more strict now what to use. It's fixable so just gotta spend some time on it!
