### ISSUE TITLE
Can't add torrent by filepath that contains square brackets

### ISSUE THREAD

**Issue by deanishe** [ludviglundgren/qbittorrent-cli#89]
`qbt` chokes on filepaths that contain square brackets (e.g. `some linux iso [123].torrent`) because it treats input as a glob pattern.

Could `qbt` check if `filePath` is actually the path of a `.torrent` file before it tries to use it as a globbing pattern?

**Comment by aca** [comment]
This was quite unexpected and critical issue for me... ( I thought I added all my torrent and removed it..)
I just created patch on my fork as you suggested.

**Comment by smammy** [comment]
This still happens in v2.2.0 (and, indeed, nothing in 19bd729 would appear to "check if file exists before globbing").
